#!/bin/bash

# shellcheck source=.bashrc
[[ -f "$HOME/.bashrc" ]] && source "$HOME/.bashrc"

[[ -f "$HOME/.zprofile" ]] && source "$HOME/.zprofile"

# do nothing if not running interactively
case $- in
    *i*) ;;
    *) return;;
esac

# code generated by script, ignore all shellcheck warnings
# shellcheck disable=2086,1091
test -e ${HOME}/.iterm2_shell_integration.bash && source ${HOME}/.iterm2_shell_integration.bash
# shellcheck disable=2086,1091
if [ -e ${HOME}/.nix-profile/etc/profile.d/nix.sh ]; then . ${HOME}/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
