empty_item_single_line = false
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternallcrate"
unstable_features = true
use_try_shorthand = true
edition = "2021"
