---
- name: 配置 SpaceVim
  block:
      - name: 配置 SpaceVim 的 git
        git:
            clone: yes
            dest: ~/.vim
            force: no
            repo: https://github.com/SpaceVim/SpaceVim.git
            recursive: yes
            track_submodules: yes
            update: yes

# TODO 安装 SpaceVim 的依赖
